;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Sprint",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Stop",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Drain",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")

